services:
  - type: web
    name: yuayuno-web
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    branch: main
    plan: free
    region: oregon
    git:
      repo: https://github.com/uyuyunanonano/yuayuno-web
